// <auto-generated />
using System;
using Kathavachak.Infrastructure.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kathavachak.Infrastructure.Migrations
{
    [DbContext(typeof(KathavachakDbContext))]
    [Migration("20251108104216_Initial-Create")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Kathavachak.Domain.Entities.KathavachakAddon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("Currency")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("INR")
                        .HasColumnName("currency");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("description");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("display_order");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<int?>("KathavachakExpertiseId")
                        .HasColumnType("int")
                        .HasColumnName("kathavachak_expertise_id");

                    b.Property<int?>("KathavachakId")
                        .HasColumnType("int")
                        .HasColumnName("kathavachak_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("price");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.HasKey("Id")
                        .HasName("pk_kathavachak_addon_id");

                    b.HasIndex("KathavachakExpertiseId");

                    b.HasIndex("KathavachakId");

                    b.ToTable("kathavachak_addon", (string)null);
                });

            modelBuilder.Entity("Kathavachak.Domain.Entities.KathavachakAttributeValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AttributeDataTypeId")
                        .HasColumnType("int")
                        .HasColumnName("attribute_data_type_id");

                    b.Property<string>("AttributeKey")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("attribute_key");

                    b.Property<string>("AttributeLabel")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("attribute_label");

                    b.Property<int?>("CatalogAttributeGroupId")
                        .HasColumnType("int")
                        .HasColumnName("catalog_attribute_group_id");

                    b.Property<int>("CatalogAttributeId")
                        .HasColumnType("int")
                        .HasColumnName("catalog_attribute_id");

                    b.Property<int>("CatalogAttributeValueId")
                        .HasColumnType("int")
                        .HasColumnName("catalog_attribute_value_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<int>("ExpertiseId")
                        .HasColumnType("int")
                        .HasColumnName("expertise_id");

                    b.Property<int?>("KathavachakId")
                        .HasColumnType("int")
                        .HasColumnName("kathavachak_id");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("KathavachakId");

                    b.HasIndex("ExpertiseId", "CatalogAttributeId")
                        .HasDatabaseName("ix_kathavachak_attribute_values_kathavachak_catalogattribute");

                    b.ToTable("kathavachak_attribute_value", (string)null);
                });

            modelBuilder.Entity("Kathavachak.Domain.Entities.KathavachakExpertise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BookingType")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("booking_type");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int")
                        .HasColumnName("duration_minute");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_default");

                    b.Property<int>("KathavachakId")
                        .HasColumnType("int")
                        .HasColumnName("kathavachak_id");

                    b.Property<decimal?>("MRP")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("mrp");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("price");

                    b.Property<int?>("StockQuantity")
                        .HasColumnType("int")
                        .HasColumnName("stock_quantity");

                    b.HasKey("Id");

                    b.HasIndex("KathavachakId");

                    b.ToTable("kathavachak_expertise", (string)null);
                });

            modelBuilder.Entity("Kathavachak.Domain.Entities.KathavachakExpertiseMedia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AltText")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("alt_text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<int>("KathavachakExpertiseId")
                        .HasColumnType("int")
                        .HasColumnName("kathavachak_expertise_id");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("media_type");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("sort_order");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.HasKey("Id");

                    b.HasIndex("KathavachakExpertiseId");

                    b.ToTable("kathavachak_expertise_image", (string)null);
                });

            modelBuilder.Entity("Kathavachak.Domain.Entities.KathavachakLanguage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("KathavachakId")
                        .HasColumnType("int")
                        .HasColumnName("kathavachak_id");

                    b.Property<int>("LanguageId")
                        .HasColumnType("int")
                        .HasColumnName("language_id");

                    b.Property<string>("LanguageName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("language_name");

                    b.HasKey("Id");

                    b.HasIndex("KathavachakId");

                    b.ToTable("kathavachak_language", (string)null);
                });

            modelBuilder.Entity("Kathavachak.Domain.Entities.KathavachakMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("category_id");

                    b.Property<string>("CategoryNameSnapshot")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("category_name_snapshot");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)")
                        .HasColumnName("currency");

                    b.Property<bool>("IsActive")
                        .HasMaxLength(50)
                        .HasColumnType("tinyint(50)")
                        .HasColumnName("is_active");

                    b.Property<bool?>("IsFeatured")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_featured");

                    b.Property<bool?>("IsTrending")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_trending");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("name");

                    b.Property<int>("Rating")
                        .HasColumnType("int")
                        .HasColumnName("rating_snap");

                    b.Property<int>("Reviews")
                        .HasColumnType("int")
                        .HasColumnName("reviews_snap");

                    b.Property<int>("SubCategoryId")
                        .HasColumnType("int")
                        .HasColumnName("sub_category_id");

                    b.Property<string>("SubCategoryNameSnapshot")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("sub_category_name_snapshot");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("thumbnail_url");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.HasKey("Id");

                    b.ToTable("kathavachak_master", (string)null);
                });

            modelBuilder.Entity("Kathavachak.Domain.Entities.KathavachakMedia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AltText")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("alt_text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<int>("KathavachakId")
                        .HasColumnType("int")
                        .HasColumnName("kathavachak_id");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("media_type");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("sort_order");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.HasKey("Id");

                    b.HasIndex("KathavachakId");

                    b.ToTable("kathavachak_image", (string)null);
                });

            modelBuilder.Entity("Kathavachak.Domain.Entities.KathavachakSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("end_date");

                    b.Property<bool>("IsAvailable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("is_available");

                    b.Property<bool>("IsRecurring")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("is_recurring");

                    b.Property<int>("KathavachakId")
                        .HasColumnType("int")
                        .HasColumnName("kathavachak_id");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("start_date");

                    b.HasKey("Id");

                    b.HasIndex("KathavachakId");

                    b.ToTable("kathavachak_schedule", (string)null);
                });

            modelBuilder.Entity("Kathavachak.Domain.Entities.KathavachakSearchRaw", b =>
                {
                    b.Property<float?>("CatScore")
                        .HasColumnType("float");

                    b.Property<int?>("CatalogAttributeDatatype")
                        .HasColumnType("int");

                    b.Property<int?>("CatalogAttributeId")
                        .HasColumnType("int");

                    b.Property<string>("CatalogAttributeKey")
                        .HasColumnType("longtext");

                    b.Property<string>("CatalogAttributeLabel")
                        .HasColumnType("longtext");

                    b.Property<string>("CatalogAttributeValue")
                        .HasColumnType("longtext");

                    b.Property<int?>("CatalogAttributeValueId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("CategoryNameSnapshot")
                        .HasColumnType("longtext");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<float?>("NameScore")
                        .HasColumnType("float");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("SubCategoryNameSnapshot")
                        .HasColumnType("longtext");

                    b.Property<float?>("SubcatScore")
                        .HasColumnType("float");

                    b.Property<int>("SubcategoryId")
                        .HasColumnType("int");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("longtext");

                    b.Property<float?>("TotalScore")
                        .HasColumnType("float");

                    b.ToTable((string)null);

                    b.ToView(null, (string)null);
                });

            modelBuilder.Entity("Kathavachak.Domain.Entities.KathavachakSessionMode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("KathavachakId")
                        .HasColumnType("int")
                        .HasColumnName("kathavachak_id");

                    b.Property<int>("Mode")
                        .HasMaxLength(100)
                        .HasColumnType("int")
                        .HasColumnName("mode_name");

                    b.HasKey("Id");

                    b.HasIndex("KathavachakId");

                    b.ToTable("kathavachak_session_mode", (string)null);
                });

            modelBuilder.Entity("Kathavachak.Domain.Entities.KathavachakTimeSlot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int")
                        .HasColumnName("day_of_week");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time(6)")
                        .HasColumnName("end_time");

                    b.Property<bool>("IsBooked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("is_booked");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("int")
                        .HasColumnName("schedule_id");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time(6)")
                        .HasColumnName("start_time");

                    b.HasKey("Id");

                    b.HasIndex("ScheduleId")
                        .HasDatabaseName("ix_time_slots_schedule_id");

                    b.ToTable("kathavachak_time_slot", (string)null);
                });

            modelBuilder.Entity("Kathavachak.Domain.Entities.KathavachakTopic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("KathavachakId")
                        .HasColumnType("int")
                        .HasColumnName("kathavachak_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("topic_name");

                    b.HasKey("Id");

                    b.HasIndex("KathavachakId");

                    b.ToTable("kathavachak_topic", (string)null);
                });

            modelBuilder.Entity("Kathavachak.Domain.Entities.KathavachakAddon", b =>
                {
                    b.HasOne("Kathavachak.Domain.Entities.KathavachakExpertise", "KathavachakExpertise")
                        .WithMany("KathavachakAddons")
                        .HasForeignKey("KathavachakExpertiseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_kathavachak_addon_kathavachak_variant_id");

                    b.HasOne("Kathavachak.Domain.Entities.KathavachakMaster", "KathavachakMaster")
                        .WithMany("KathavachakAddons")
                        .HasForeignKey("KathavachakId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_kathavachak_addons_kathavachak_id");

                    b.Navigation("KathavachakExpertise");

                    b.Navigation("KathavachakMaster");
                });

            modelBuilder.Entity("Kathavachak.Domain.Entities.KathavachakAttributeValue", b =>
                {
                    b.HasOne("Kathavachak.Domain.Entities.KathavachakExpertise", "KathavachakExpertise")
                        .WithMany("KathavachakAttributeValues")
                        .HasForeignKey("ExpertiseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_kathavachak_attribute_value_expertise_id");

                    b.HasOne("Kathavachak.Domain.Entities.KathavachakMaster", "KathavachakMaster")
                        .WithMany("AttributeValues")
                        .HasForeignKey("KathavachakId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("KathavachakExpertise");

                    b.Navigation("KathavachakMaster");
                });

            modelBuilder.Entity("Kathavachak.Domain.Entities.KathavachakExpertise", b =>
                {
                    b.HasOne("Kathavachak.Domain.Entities.KathavachakMaster", "KathavachakMaster")
                        .WithMany("KathavachakExpertises")
                        .HasForeignKey("KathavachakId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KathavachakMaster");
                });

            modelBuilder.Entity("Kathavachak.Domain.Entities.KathavachakExpertiseMedia", b =>
                {
                    b.HasOne("Kathavachak.Domain.Entities.KathavachakExpertise", "KathavachakExpertise")
                        .WithMany("KathavachakExpertiseMedia")
                        .HasForeignKey("KathavachakExpertiseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KathavachakExpertise");
                });

            modelBuilder.Entity("Kathavachak.Domain.Entities.KathavachakLanguage", b =>
                {
                    b.HasOne("Kathavachak.Domain.Entities.KathavachakMaster", "Kathavachak")
                        .WithMany("Languages")
                        .HasForeignKey("KathavachakId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_kathavachak_language_kathavachak_id");

                    b.Navigation("Kathavachak");
                });

            modelBuilder.Entity("Kathavachak.Domain.Entities.KathavachakMedia", b =>
                {
                    b.HasOne("Kathavachak.Domain.Entities.KathavachakMaster", "KathavachakMaster")
                        .WithMany("KathavachakMedia")
                        .HasForeignKey("KathavachakId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KathavachakMaster");
                });

            modelBuilder.Entity("Kathavachak.Domain.Entities.KathavachakSchedule", b =>
                {
                    b.HasOne("Kathavachak.Domain.Entities.KathavachakMaster", "Kathavachak")
                        .WithMany("Schedules")
                        .HasForeignKey("KathavachakId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kathavachak");
                });

            modelBuilder.Entity("Kathavachak.Domain.Entities.KathavachakSessionMode", b =>
                {
                    b.HasOne("Kathavachak.Domain.Entities.KathavachakMaster", "Kathavachak")
                        .WithMany("SessionModes")
                        .HasForeignKey("KathavachakId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kathavachak");
                });

            modelBuilder.Entity("Kathavachak.Domain.Entities.KathavachakTimeSlot", b =>
                {
                    b.HasOne("Kathavachak.Domain.Entities.KathavachakSchedule", "Schedule")
                        .WithMany("TimeSlots")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("Kathavachak.Domain.Entities.KathavachakTopic", b =>
                {
                    b.HasOne("Kathavachak.Domain.Entities.KathavachakMaster", "Kathavachak")
                        .WithMany("Topics")
                        .HasForeignKey("KathavachakId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kathavachak");
                });

            modelBuilder.Entity("Kathavachak.Domain.Entities.KathavachakExpertise", b =>
                {
                    b.Navigation("KathavachakAddons");

                    b.Navigation("KathavachakAttributeValues");

                    b.Navigation("KathavachakExpertiseMedia");
                });

            modelBuilder.Entity("Kathavachak.Domain.Entities.KathavachakMaster", b =>
                {
                    b.Navigation("AttributeValues");

                    b.Navigation("KathavachakAddons");

                    b.Navigation("KathavachakExpertises");

                    b.Navigation("KathavachakMedia");

                    b.Navigation("Languages");

                    b.Navigation("Schedules");

                    b.Navigation("SessionModes");

                    b.Navigation("Topics");
                });

            modelBuilder.Entity("Kathavachak.Domain.Entities.KathavachakSchedule", b =>
                {
                    b.Navigation("TimeSlots");
                });
#pragma warning restore 612, 618
        }
    }
}
