// <auto-generated />
using System;
using Catalog.Infrastructure.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Catalog.Infrastructure.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    partial class CatalogDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Catalog.Domain.Entities.CategoryLocalizedText", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("category_id");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("language_code");

                    b.Property<string>("LocalizedDescription")
                        .HasColumnType("longtext")
                        .HasColumnName("localized_description");

                    b.Property<string>("LocalizedName")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("localized_name");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("category_localized_text", (string)null);
                });

            modelBuilder.Entity("Catalog.Domain.Entities.CategoryMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("description");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int")
                        .HasColumnName("display_order");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("category_master", (string)null);
                });

            modelBuilder.Entity("Catalog.Domain.Entities.PoojaKitItemLocalizedText", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("language_code");

                    b.Property<string>("LocalizedDescription")
                        .HasColumnType("longtext")
                        .HasColumnName("localized_description");

                    b.Property<string>("LocalizedName")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("localized_name");

                    b.Property<int>("PoojaKitId")
                        .HasColumnType("int")
                        .HasColumnName("pooja_kit_id");

                    b.HasKey("Id");

                    b.HasIndex("PoojaKitId");

                    b.ToTable("pooja_kit_item_localized_text", (string)null);
                });

            modelBuilder.Entity("Catalog.Domain.Entities.PoojaKitItemMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("item_name");

                    b.Property<int>("PoojaKitMasterId")
                        .HasColumnType("int")
                        .HasColumnName("pooja_kit_master_id");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("quantity");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("PoojaKitMasterId");

                    b.ToTable("pooja_kit_item_master", (string)null);
                });

            modelBuilder.Entity("Catalog.Domain.Entities.PoojaKitLocalizedText", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("language_code");

                    b.Property<string>("LocalizedDescription")
                        .HasColumnType("longtext")
                        .HasColumnName("localized_description");

                    b.Property<string>("LocalizedName")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("localized_name");

                    b.Property<int>("PoojaKitId")
                        .HasColumnType("int")
                        .HasColumnName("pooja_kit_id");

                    b.HasKey("Id");

                    b.HasIndex("PoojaKitId");

                    b.ToTable("pooja_kit_localized_text", (string)null);
                });

            modelBuilder.Entity("Catalog.Domain.Entities.PoojaKitMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("name");

                    b.Property<int>("SubCategoryMasterId")
                        .HasColumnType("int")
                        .HasColumnName("sub_category_master_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("SubCategoryMasterId");

                    b.ToTable("pooja_kit_master", (string)null);
                });

            modelBuilder.Entity("Catalog.Domain.Entities.SubCategoryLocalizedText", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("language_code");

                    b.Property<string>("LocalizedDescription")
                        .HasColumnType("longtext")
                        .HasColumnName("localized_description");

                    b.Property<string>("LocalizedName")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("localized_name");

                    b.Property<int>("SubCategoryId")
                        .HasColumnType("int")
                        .HasColumnName("sub_category_id");

                    b.HasKey("Id");

                    b.HasIndex("SubCategoryId");

                    b.ToTable("sub_category_localized_text", (string)null);
                });

            modelBuilder.Entity("Catalog.Domain.Entities.SubCategoryMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryMasterId")
                        .HasColumnType("int")
                        .HasColumnName("category_master_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CategoryMasterId");

                    b.ToTable("sub_category_master", (string)null);
                });

            modelBuilder.Entity("Catalog.Domain.Entities.CategoryLocalizedText", b =>
                {
                    b.HasOne("Catalog.Domain.Entities.CategoryMaster", "Category")
                        .WithMany("Localizations")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Catalog.Domain.Entities.PoojaKitItemLocalizedText", b =>
                {
                    b.HasOne("Catalog.Domain.Entities.PoojaKitItemMaster", "PoojaKitItem")
                        .WithMany("Localizations")
                        .HasForeignKey("PoojaKitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PoojaKitItem");
                });

            modelBuilder.Entity("Catalog.Domain.Entities.PoojaKitItemMaster", b =>
                {
                    b.HasOne("Catalog.Domain.Entities.PoojaKitMaster", "PoojaKitMaster")
                        .WithMany("PoojaKitItems")
                        .HasForeignKey("PoojaKitMasterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PoojaKitMaster");
                });

            modelBuilder.Entity("Catalog.Domain.Entities.PoojaKitLocalizedText", b =>
                {
                    b.HasOne("Catalog.Domain.Entities.PoojaKitMaster", "PoojaKit")
                        .WithMany("Localizations")
                        .HasForeignKey("PoojaKitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PoojaKit");
                });

            modelBuilder.Entity("Catalog.Domain.Entities.PoojaKitMaster", b =>
                {
                    b.HasOne("Catalog.Domain.Entities.SubCategoryMaster", "SubCategoryMaster")
                        .WithMany("PoojaKits")
                        .HasForeignKey("SubCategoryMasterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubCategoryMaster");
                });

            modelBuilder.Entity("Catalog.Domain.Entities.SubCategoryLocalizedText", b =>
                {
                    b.HasOne("Catalog.Domain.Entities.SubCategoryMaster", "SubCategory")
                        .WithMany("Localizations")
                        .HasForeignKey("SubCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubCategory");
                });

            modelBuilder.Entity("Catalog.Domain.Entities.SubCategoryMaster", b =>
                {
                    b.HasOne("Catalog.Domain.Entities.CategoryMaster", "CategoryMaster")
                        .WithMany("SubCategoryMasters")
                        .HasForeignKey("CategoryMasterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategoryMaster");
                });

            modelBuilder.Entity("Catalog.Domain.Entities.CategoryMaster", b =>
                {
                    b.Navigation("Localizations");

                    b.Navigation("SubCategoryMasters");
                });

            modelBuilder.Entity("Catalog.Domain.Entities.PoojaKitItemMaster", b =>
                {
                    b.Navigation("Localizations");
                });

            modelBuilder.Entity("Catalog.Domain.Entities.PoojaKitMaster", b =>
                {
                    b.Navigation("Localizations");

                    b.Navigation("PoojaKitItems");
                });

            modelBuilder.Entity("Catalog.Domain.Entities.SubCategoryMaster", b =>
                {
                    b.Navigation("Localizations");

                    b.Navigation("PoojaKits");
                });
#pragma warning restore 612, 618
        }
    }
}
